import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useApp } from "../context/AppContext";
import { formatMoney } from "../lib/currency";
import * as api from "../lib/api";
import { ArrowLeft, Flag, Swords, Target, Trophy, Wifi } from "lucide-react";

export default function PlayerPage() {
  const { username } = useParams();
  const navigate = useNavigate();
  const { user, currency } = useApp();
  const [profile, setProfile] = useState(null);
  const [error, setError] = useState("");
  useEffect(() => { api.getPlayerProfile(username).then(setProfile).catch((requestError) => setError(requestError.message)); }, [username]);
  const report = async () => { if (!window.confirm(`Signaler ${username} pour comportement inapproprié ?`)) return; try { await api.reportPlayer(username, "OTHER", "Signalement depuis le profil public"); setError("Signalement transmis à la modération."); } catch (requestError) { setError(requestError.message); } };
  if (!profile) return <div className="min-h-screen px-5 py-8"><button onClick={() => navigate(-1)} className="btn-ghost">← Retour</button><p className="mt-12 text-center">{error || "Chargement du profil…"}</p></div>;
  const initials = profile.username.slice(0,2).toUpperCase();
  return <div className="min-h-full px-4 sm:px-6 py-8 max-w-3xl mx-auto space-y-6"><button onClick={() => navigate(-1)} className="btn-ghost inline-flex items-center gap-2"><ArrowLeft className="h-4 w-4" />Retour</button><header className="card rounded-3xl p-6"><div className="flex items-center gap-5"><div className="grid h-20 w-20 place-items-center rounded-full text-xl font-extrabold" style={{ background: "var(--accent-soft)", color: "var(--accent)" }}>{initials}</div><div className="min-w-0 flex-1"><h1 className="truncate font-display text-4xl font-extrabold">{profile.username}</h1><p className="mt-1 inline-flex items-center gap-1 text-sm" style={{ color: profile.online ? "var(--success)" : "var(--text-sub)" }}><Wifi className="h-4 w-4" />{profile.online ? "En ligne" : "Hors ligne"}</p></div></div>{profile.username !== user?.name && <div className="mt-6 flex gap-2"><button disabled={!profile.online} onClick={() => navigate("/duel", { state: { challengeUsername: profile.username } })} className="btn-primary inline-flex items-center gap-2 rounded-xl px-5 py-3 disabled:opacity-40"><Swords className="h-4 w-4" />Défier</button><button onClick={report} className="btn-secondary inline-flex items-center gap-2 rounded-xl px-5 py-3"><Flag className="h-4 w-4" />Signaler</button></div>}</header><section className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat icon={Swords} label="Duels" value={profile.stats.duelsPlayed} /><Stat icon={Trophy} label="Victoires" value={profile.stats.duelsWon} /><Stat icon={Target} label="Réussite" value={`${profile.stats.winRateGlobal}%`} /><Stat icon={Trophy} label="Gains" value={formatMoney(profile.stats.winningsCoins, currency)} /></section><section><h2 className="mb-3 font-display text-2xl font-bold">Duels récents</h2><div className="card overflow-hidden rounded-2xl">{profile.recentDuels.length ? profile.recentDuels.map((match) => <div key={match.id} className="grid grid-cols-[1fr_auto] gap-3 border-b px-4 py-3 last:border-0" style={{ borderColor: "var(--divider)" }}><div><strong>{match.playerA} vs {match.playerB}</strong><p className="mt-1 text-xs" style={{ color: "var(--text-sub)" }}>{new Date(match.completedAt).toLocaleString("fr-FR")}</p></div><strong style={{ color: "var(--accent)" }}>{match.scoreA}–{match.scoreB}</strong></div>) : <p className="p-6 text-center text-sm" style={{ color: "var(--text-sub)" }}>Aucun duel terminé.</p>}</div></section>{error && <p className="text-sm" style={{ color: error.includes("transmis") ? "var(--success)" : "var(--danger)" }}>{error}</p>}</div>;
}
function Stat({ icon: Icon, label, value }) { return <div className="card rounded-2xl p-4"><Icon className="h-4 w-4 text-orange-qa" /><p className="mt-2 text-xs" style={{ color: "var(--text-sub)" }}>{label}</p><strong className="mt-1 block text-lg">{value}</strong></div>; }
