import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useApp } from "../context/AppContext";
import * as api from "../lib/api";
import { BookOpen, RotateCcw, Swords, Target, Trophy, Zap } from "lucide-react";

export default function Profile() {
  const navigate = useNavigate();
  const { user, stats, elo, resetOnboarding, refreshSession } = useApp();
  const [history, setHistory] = useState([]);
  useEffect(() => { refreshSession().catch(() => {}); api.getQuizHistory().then((result) => setHistory(result.history || [])).catch(() => {}); }, [refreshSession]);
  const initials = (user?.name || "J").slice(0, 2).toUpperCase();
  return <div className="min-h-full px-4 sm:px-6 py-8 max-w-4xl mx-auto space-y-7"><header className="card rounded-3xl p-6"><div className="flex items-center gap-5"><div className="grid h-20 w-20 place-items-center rounded-full text-2xl font-extrabold" style={{ background: "var(--accent-soft)", color: "var(--accent)" }}>{initials}</div><div><h1 className="font-display text-4xl font-extrabold">{user?.name}</h1><p className="mt-1 text-sm" style={{ color: "var(--text-sub)" }}>Membre depuis {user?.createdAt ? new Date(user.createdAt).toLocaleDateString("fr-FR") : "—"}</p></div></div></header><section className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat icon={Swords} label="Parties" value={stats?.totalGames ?? 0} /><Stat icon={Trophy} label="Victoires" value={`${stats?.winRateGlobal ?? 0}%`} /><Stat icon={Target} label="Score moyen" value={stats?.avgScore ?? 0} /><Stat icon={Zap} label="ELO" value={elo} /></section><section><h2 className="mb-4 font-display text-2xl font-bold">Quiz récents</h2><div className="card overflow-hidden rounded-2xl">{history.length ? history.slice(0, 10).map((item) => <div key={item.id} className="grid grid-cols-[1fr_auto] gap-3 border-b px-4 py-3 last:border-0" style={{ borderColor: "var(--divider)" }}><div><strong>{item.categoryName}</strong><p className="mt-1 text-xs" style={{ color: "var(--text-sub)" }}>{item.mode} · {new Date(item.startedAt).toLocaleDateString("fr-FR")}</p></div><strong style={{ color: "var(--accent)" }}>{item.scoreServer}/{item.totalQuestions}</strong></div>) : <p className="p-6 text-center text-sm" style={{ color: "var(--text-sub)" }}>Aucune partie solo terminée.</p>}</div></section><div className="grid gap-3 sm:grid-cols-3"><Action icon={RotateCcw} label="Historique des duels" onClick={() => navigate("/replays")} /><Action icon={BookOpen} label="Règles" onClick={() => navigate("/rules")} /><Action icon={Zap} label="Revoir le tutoriel" onClick={() => { resetOnboarding(); navigate("/"); }} /></div></div>;
}
function Stat({ icon: Icon, label, value }) { return <div className="card rounded-2xl p-4"><Icon className="h-4 w-4" style={{ color: "var(--accent)" }} /><p className="mt-3 text-xs" style={{ color: "var(--text-sub)" }}>{label}</p><strong className="mt-1 block text-2xl">{value}</strong></div>; }
function Action({ icon: Icon, label, onClick }) { return <button onClick={onClick} className="card card-hover flex items-center gap-3 rounded-2xl p-4 text-left"><Icon className="h-5 w-5" style={{ color: "var(--accent)" }} /><strong className="text-sm">{label}</strong></button>; }
